home/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from home import views
# from .views import MobileDetailView

urlpatterns = [
    path('',views.index,name='index'),
    path('phone_form/',views.phone_entry_form,name='phone_entry_form'), 
    # path('delete/<int:idd>',views.delete,name='delete'),               // admin can delete any item 
    path('deleteitem/<int:idd>',views.deleteitem,name='deleteitem'),
    path('loginpage/',views.loginUser,name='loginpage'),
    path('homepage/',views.homepage,name='homepage'),
    path('logout/',views.logout,name='logout'),
    path('contact/',views.contact,name='contact'),
    path('profile/',views.profile,name='profile'),
    path('signup',views.signup,name='signup'),
    path('tag/',views.tag,name='tag'),
    path('mobile_details/<int:idd>',views.mobile_details,name='mobile_details'),
    path('add_to_cart/',views.add_to_cart,name='add_to_cart'),
    path('about/',views.about,name='about'),
    path('product/<int:product_id>',views.product,name='product'),
    # path('index1/',views.index1,name='index1'),
    path('mobile_like/<int:pk>',views.mobile_like, name='mobile_like')




] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

mobile/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls'))
]

home/models.py
from re import L
from typing_extensions import Required
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#this  model  is for filter
class Tag(models.Model):
    tag=models.CharField(max_length=20)
    profile=models.ImageField(upload_to='media/images/',null=True,default=None)
    def __str__(self):
        return self.tag        



# This is a model by which anyuser can fill details to contact with us  
class Contact(models.Model):
    name=models.CharField(max_length=20)
    city=models.CharField(max_length=20)      
    mob_no=models.IntegerField()  
    message=models.CharField(max_length=500)  
    def __str__(self):
        return self.name

#  to add anew customer
class Customer(models.Model):
    # user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200)
    pswd=models.CharField(max_length=20,null=True)
    


    @staticmethod
    def get_customer_by_email(email):
        try:
            return Customer.objects.get(email=email)
        except:
            False    
        

    def isExists(self):
       if Customer.objects.filter(email = self.email):
            return True

       return  False


# Order model
class Order(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False)
	transaction_id = models.CharField(max_length=100, null=True)

	def __str__(self):
		return str(self.id)    

# This is address of any customer
class ShippingAddress(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	state = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.address 






# this is a product model 
class Mobile(models.Model):
    phone=models.CharField(max_length=50)
    brand=models.CharField(max_length=20)
    ram=models.CharField(max_length=10)
    color=models.CharField(max_length=20)
    image=models.ImageField(upload_to='media/images/',null=True,default=None)
    price=models.CharField(max_length=5,null=True)
    date=models.DateField(null=True,default=None)
    tags=models.ManyToManyField(Tag,default=None)
    like=models.ManyToManyField(Customer,related_name='mobiles',blank=True, null=True,default=None)
    def __str__(self):
        return self.phone   

    def total_like(self):
        return self.like.count()         

# order item model for cart 
class OrderItem(models.Model):
    product = models.ForeignKey(Mobile, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    # price=models.OneToOneField(Mobile,on_delete=models.SET_NULL,null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.product)
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total      

class Product(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField()
    image_url = models.CharField(max_length=100)             

templates/add_to_cart.html
{% extends 'base.html' %}

{% block title %}
Cart
{% endblock title%}

{% block body %}

<section class="h-100 gradient-custom">
    <div class="container py-5">
      <div class="row d-flex justify-content-center my-4">
        <div class="col-md-8">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Cart - 2 items</h5>
            </div>
            <div class="card-body">
  
              <hr class="my-4" />
             {% for carts in cart %}
              <!-- Single item -->
              <div class="row">
                <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                  <!-- Image -->
                  <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                    <img src="{{carts.image.url}}"
                      class="w-100" />
                    <a href="#!">
                      <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                    </a>
                  </div>
                  <!-- Image -->
                </div>
  
                <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                  <!-- Data -->
                  <p>{{carts.id}}</p>
                  <p><strong>{{carts.product}}</strong></p>
              
  
                  <a href="{% url 'deleteitem' carts.id %}"><button type="button" class="btn btn-primary btn-sm me-1 mb-2" data-mdb-toggle="tooltip"
                    title="Remove item">
                    Remove
                  </button></a>
                  <!-- Data -->
                </div>
  
                <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                  <!-- Quantity -->
                  <div class="d-flex mb-4" style="max-width: 300px">
                    <button class="btn btn-primary px-3 me-2"
                      onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                      <i class="fas fa-minus"><strong>-</strong></i>
                    </button>
  
                    <div class="form-outline">
                      <input id="form1" min="0" name="quantity" value="1" type="number" class="form-control" />
                      <label class="form-label" for="form1">{{carts.Quantity}}</label>
                    </div>
  
                    <button class="btn btn-primary px-3 ms-2"
                      onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                      <i class="fas fa-plus"><strong>+</strong></i>
                    </button>
                  </div>
                  <!-- Quantity -->
  
                  <!-- Price -->
                  <p class="text-start text-md-center">
                    <strong></strong>
                  </p>
                  <!-- Price -->
                </div>
                {% endfor %}
              </div>
              <!-- Single item -->
            </div>
          </div>
          <div class="card mb-4">
            <div class="card-body">
              <p><strong>Expected shipping delivery</strong></p>
              <p class="mb-0">12.10.2020 - 14.10.2020</p>
            </div>
          </div>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body">
              <p><strong>We accept</strong></p>
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                alt="Visa" />
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                alt="American Express" />
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                alt="Mastercard" />
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.webp"
                alt="PayPal acceptance mark" />
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Summary</h5>
            </div>
            <div class="card-body">
              <ul class="list-group list-group-flush">
                <li
                  class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                  Products
                  <span>$53.98</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                  Shipping
                  <span>Gratis</span>
                </li>
                <li
                  class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                  <div>
                    <strong>Total amount</strong>
                    <strong>
                      <p class="mb-0">(including VAT)</p>
                    </strong>
                  </div>
                  <span><strong>$53.98</strong></span>
                </li>
              </ul>
  
              <button type="button" class="btn btn-primary btn-lg btn-block">
                Go to checkout
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock body %}

templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <title>{% block title %} {% endblock title%}</title>
  <!-- Vendor CSS -->
  <!-- Custom styles for this template -->
  <!-- Custom font -->
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



    {% block style %} 
        
    {% endblock style %}
  
 
  </head>
    {% include 'navbar.html' %}

    <!-- Option 1: Bootstrap Bundle with Popper -->


    {% block body %} <h1> Header block </h1>{% endblock body %}


    {% include 'footer.html' %}

    {% block js %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% endblock %}
  </body>
		  
 
  
	
  
  </html>

templates/contact.html
{% extends 'base.html' %}

{% block title %} 
Login
{% endblock title %}

{% block style %} 

{% endblock style %}

{% block body %}

<div class="container" style="margin-top:20px;  margin-bottom:120px; border: 5px solid cyan;background:khaki;">
<form method="POST" action="" style='margin:50px;'>
    {% csrf_token %}
    <div class="row">
       <div class='col-md-1'>
        <label for ='name'>Name :</label>
       </div>
       <div class='col-md-5'>
        {{form.name}}
       </div>
        <div class='col-md-1'>

            <label for ='city'>City :</label>
            </div>
            <div class='col-md-5'>

             {{form.city}}
      </div>
    </div>



    <div class="row" style='margin-top:20px;'>
        <div class='col-md-1'>
         <label for ='mobile '>Mobile : </label>
        </div>
        <div class='col-md-5'>

         {{form.mob_no}}
      </div>
    
        <div class='col-md-1'
         <label for ='message'>message:</label>
    </div>
    <div class='col-md-5'>
         {{form.message}}
    </div>
    </div>
   
    <div class='row' style='margin-top:20px;'>
        
        
     <div class='col-md-3'>
        </div>
        <button class='col-md-4' type='submit' value='submit'>Submit</button> 
    </div>
</form>
</div>

{% endblock body %}

templates/entry_form.html
{% extends 'base.html' %}

{% block title %}
Mobile Form
{% endblock title%}

{% block body %}

<div class='container' style='margin-top:20px;'>


    {% comment %} <form>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="phone">Phone</label>
            <input type="text" class="form-control" name='phone'id="phone" placeholder="9877546544">
          </div>
          <div class="form-group col-md-6">
            <label for="brand">brand</label>
            <input type="text" class="form-control" name='brand' id="brand" placeholder="brand">
          </div>
        </div>
        <div class="form-group">
          <label for="ram">RAM</label>
          <input type="text" class="form-control" name='ram'id="ram" placeholder="gb">
        </div>
        <div class="form-group">
          <label for="color">color</label>
          <input type="text" class="form-control" id="color" name='color' placeholder="color">
        </div>
        <div class="form-group">
            <label for="tag">Tag</label>
            <input type="text" class="form-control" id="tag" name='tag' placeholder="tag">
          </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="date">Date</label>
            <input type="date" class="form-control" id="date" name='date'>
          </div>
          <div class="form-group col-md-2">
            <label for="image">Image</label>
            <input type="file" class="form-control" id="image" name='image'>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Sign in</button>
      </form> {% endcomment %}


  

<form method="post" action=""  enctype="multipart/form-data">
    {% csrf_token %}

     <div class='row'>
      <div class=col-md-1>
           <label for='phone'>Phone</label>
      </div>
      <div class=col-md-5>
         {{form.phone}}
      </div>
      <div class=col-md-1>
           <label for='color'>color</label>
      </div>
      <div class=col-md-5>
          {{form.color}}
      </div>
  </div>


  <div class='row'>
    <div class='col-md-1'>
    <label for='brand'>brand</label>
    </div>
    <div class='col-md-5'>
    {{form.brand}}
    </div>
    <div class='col-md-1'>
    <label for='ram'>ram</label>
    </div>
    <div class='col-md-5'>
    {{form.ram}}
    </div>
  </div>


  <div class='row'>
    <div class='col-md-1'>
        <label for='date'>date</label>
    </div>
    <div class='col-md-5'>
    {{form.date}}
    <label for='price'>price</label>
    {{form.price}}

    <label for='Image'>Image</label>
     {{form.image}}


    <label for="tag">tag</label>
   {{form.tags}}  
    <button type='submit' value='submit'>Submit</button>
</form>
</div>


<script>
  $(document).ready(function() {
    $('#id_tags').select2();
});
</script>
{% endblock body%}

templates/footer.html
<div class="card bg-dark text-white">
    <img class="card-img" src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeFzkShOyMneuIL65WhSavXxXVepZOM4M3iA&usqp=CAU' style='height:300px'alt="Card image">
    <div class="card-img-overlay">
      <h2 class="card-title">Mobi$tore</h2>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text">Last updated 3 mins ago</p>
      <div class="row" style=" margin: auto;
      width: 50%;
      color:white;
      padding: 10px;">
        <div class="column">
      <div class="collapsed-content" >
        <ul>
          <li><a href="/about"style="color:white;">About Us</a></li>
          <li><a href="/contact"style="color:white;">Contact Us</a></li>
          <li><a href="typography.html" style="color:white;">Terms & Conditions</a></li>
          <li><a href="typography.html"style="color:white;">Returns & Exchanges</a></li>
          <li><a href="typography.html"style="color:white;">Shipping & Delivery</a></li>
        </ul>
      </div>
    </div>
    <div class="column">
      <div class="collapsed-content">
        <ul>
          <li><a href="account-details.html" style="color:white;">My Account</a></li>
          <li><a href="cart.html"style="color:white;">View Cart</a></li>
          <li><a href="account-wishlist.html"style="color:white;">My Wishlist</a></li>
          <li><a href="account-history.html" style="color:white;">Order Status</a></li>
          <li><a href="account-history.html"style="color:white;">Track My Order</a></li>
        </ul>
      </div>
    </div>
    <div class="column">
        <div class="collapsed-content">
          <ul>
            <li><a href="account-details.html" style="color:white;">My Account</a></li>
            <li><a href="cart.html"style="color:white;">View Cart</a></li>
            <li><a href="account-wishlist.html"style="color:white;">My Wishlist</a></li>
            <li><a href="account-history.html" style="color:white;">Order Status</a></li>
            <li><a href="account-history.html"style="color:white;">Track My Order</a></li>
          </ul>
        </div>
      </div>
</div>

    </div>
    </div>
    <div class="footer-bottom footer-bottom--bg">
    
        <div class="footer-copyright text-center" style="background-color:grey;">
          <a href="https://github.com/vikas05kushwaha" style='color:white;'>Mobi$tore ©2020 copyright All rights reserved to Mobi$tore created by  VIkas Kushwaha</a>
        
      </div>
    </div>
  </div>

templates/homepage.html
{% extends 'base.html' %}
{% block title %} 
Login
{% endblock title %}

{% block style %} 

{% endblock style %}

{% block body %}
{% load static %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'homepage.jpg' %}" height="500px" width="700px" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'home2.jpg' %}" height="500px" width="700px"  alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'home3.jpg' %}"height="500px" width="700px"  alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  {% endblock body %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
    <style>
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .image {
            width: 100px;
            height: 100px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Products</h1>
        {% for product in products %}
        <img class="image" src="{{ product.image_url }}" />
        <a href="{% url 'product' product.id %}"><h3>{{product.title}}</h3></a>
        {% endfor %}
    </div>    
</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block title %} 
Login
{% endblock title %}

{% block style %} 


{% endblock style %}

{% block body %}

{% comment %} <div class='main' style='background-image:url(/home/vikas/mobile/static/WhatsApp Image 2022-05-18 at 1.23.21 AM.jpeg);' {% endcomment %}

<div class="container" style="margin-top:20px; height:250px;width:400px;  margin-bottom:110px; border: 5px solid blue;background:#ffcdad;">
    <form method="POST" action="" style='margin:5px;'>
        {% csrf_token %}
        <div class='row' style='margin-top:20px;'>
        <div class='col-md-4'>
         <label for='email'><legend>Email</legend></label>
        </div>
        <div class='col-md-8'>
        <input type='text' id='email' name='email' placeholder='example@gmail.com' >
        </div>
        </div>
        <div class='row' style='margin-top:40px;'>
            <div class='col-md-4'>
        <label for='password'><legend>Password</legend></label>
            </div>
            <div class='col-md-8'>
        <input type='password' id='password' name='pswd' placeholder='pass@tr23'>
            </div>
        </div>
        <div class='row' style='margin-top:20px;'>
            <div class='col-md-4'>
            </div>
    
        <button class='col-md-4' type='submit' value='submit'>Submit</button> 
       </div>
    </form>
</div>

{% endblock body %}

templates/mobile_details.html
{% extends 'base.html' %}

{% block title %}
Cart
{% endblock title%}

{% block body %}

<section style="background-color: #eee;">
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6 col-xl-4">
          <div class="card text-black">
            <i class="fab fa-apple fa-lg pt-3 pb-1 px-3"></i>
            <img src="{{mobile.image.url}}"
              class="card-img-top" alt="Apple Computer" />
            <div class="card-body">
              <div class="text-center">
                <h5 class="card-title">{{mobile.id}}</h5>
                <p class="text-muted mb-4">{{mobile.phone}}</p>
              </div>
              <div>
                <div class="d-flex justify-content-between">
                  <span>ram</span><span>{{mobile.ram}}</span>
                </div>
                <div class="d-flex justify-content-between">
                    <span>created date</span><span>{{mobile.date}}</span>
                  </div>
                <div class="d-flex justify-content-between">
                  <span>Price</span><span>{{mobile.price}}</span>
                </div>
                <div class="d-flex justify-content-between">
                    <span>Tag</span><span>{{mobile.tag}}</span>
                  </div>
                <div class="d-flex justify-content-between">
                  <span>Color</span><span>{{mobile.color}}</span>
                </div>
                <div class="d-flex justify-content-between">
                    <span>brand</span><span>{{mobile.brand}}</span>
                  </div>
              </div>
              <div class="d-flex justify-content-between total font-weight-bold mt-4">
                <span>Total</span><span>{{mobile.price}}</span>
              </div>
              <form action="{% url 'mobile_like' mobile.pk %}" method='POST'>

                {% csrf_token %}
                <button type='submit' name='mobile_id' value='{{mobile.id}}'>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                  <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                </svg>

                </button>

              </form>
              
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </section>
  <div class="container">
    <div class="row">
        <div class="column">

          <button>{{mobile.tags}}</button>
<button type="button" class="btn btn-warning">
  
    <a href="{% url 'add_to_cart' %}">Add to Cart</a></button>
</div></div></div>

{% endblock body %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'homepage' %}">Mobi$tore</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'add_to_cart' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Our Products</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'about' %}">About Us</a>
            <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
            <a class="dropdown-item" href="#">Our Team</a>
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>&nbsp
        <a href="/signup" class="btn btn-outline-success my-2 my-sm-0">Sign Up</a>&nbsp


        <div class="dropdown">
          
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{user.username}}
            </button>
            
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="/profile">profile</a>
              <a class="dropdown-item" href="/logout">logoutUser</a>
            </div>
          </div>
      </form>
     
      
     
    </div>
  </nav>

templates/tagform.html
{% extends 'base.html' %}

{% block title %} 
Tag
{% endblock title %}

{% block style %} 

{% endblock style %}

{% block body %}

<div class="container" style="margin:20px;">
<form method="POST" action="">
    {% csrf_token %}
   <div class="container" style=' margin-top:20px;'>
    <label for='tag'>tag</label>
    <input type='text' id='tag' name='tag'>

    <label for='profile'>Picture</label>
    <input type='file' id='picture' name='picture'>
   

    <button type='submit' value='submit'>Submit</button> 
   </div>
</form>
</div>

{% endblock body %}